config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
  end
  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get '/users', to: "devise/sessions#create"
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments
  post 'payments/create'
  
  post 'orders/show'

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  
  
  root 'static_pages#landing_page'

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comments

  validates :name, presence: true
  	  
  def average_rating
    comments.average(:rating).to_f
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  
  # GET /products
  # GET /products.json
  def index
    if params[:q]
    search_term = params[:q]
    @products = Product.where("name LIKE ?", "%#{search_term}%")
    else
    @products = Product.all
    end

    respond_with @products
  end
  
# GET /products/1
# GET /products/1.json
def show
    @product = Product.find(params[:id])
    
    @comments = @product.comments.order('created_at DESC').page(params[:page]).per_page(3)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end
  
  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
  def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="col-sm-7">

<h2> Comments</h2>

<div class="product-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
          <hr>
            <p><%= comment.user.first_name %><small><em><%= " #{time_ago_in_words(comment.created_at)} ago" %></em></small>
            	<% if signed_in? && current_user.try(:admin?) %>
            	<%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            	 <% end %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>
<%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
  <%= f.label :price %><br>
  <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<div class="row">

<div class="col-sm-6">
<% if signed_in? %>

  <h4>Add a review:</h4>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <p>
      <%= f.label :body, "Comment" %><br>
      <%= f.text_area :body, class: "form-control" %>
    </p>
    
  <p>
    <div class="rating"></div>
  </p>

    <p>
      <%= f.submit "Submit", class: "btn btn-default navbar-btn" %>
    </p>
  <% end %>

<% else %>

<p> Add a review? Pleae  <%= link_to('Login', new_user_session_path)  %>  </p>

<% end %>


</div>
</div>

app/views/products/edit.html.erb
<div class="container">
<h1>Editing product</h1>

<%= render 'form' %>
<br>

<p><%= link_to 'Show', @product, class: "btn btn-default navbar-btn" %>|
<%= link_to 'Back', products_path, class: "btn btn-default navbar-btn" %><p>

</div>

app/views/products/index.html.erb
<div class="container">
  <h1>Listing products</h1>

<% cache(cache_key_for_products) do %>
    <%= render "shared/product" %>
<% end %>


<br>

<p><%= link_to 'New Product', new_product_path, class: "btn btn-default navbar-btn" %> &raquo;</p>

</div>

app/views/products/new.html.erb
<div class="container">
<h1>New product</h1>

<%= render 'form' %>

<br>


<p><%= link_to 'Back', products_path, class: "btn btn-default navbar-btn"%><p>
</div>

app/views/products/show.html.erb
<div class="container">

 <h1>Product Information</h1>
 <div class="row">
  <% cache @product do %>
    <p><%= image_tag(@product.image_url, id:"zoom", class: "product_img col-md-4 img-zoom",data_zoom_image:@product.image_url) %></p>
    <h2>
      <%= @product.name %>
    </h2>
     <% logger.debug "ProductID: #{@product.id}"%>
    <p><span class="glyphicon glyphicon-leaf"></span> <%= @product.description %></p>

    <p>
      <span class="glyphicon glyphicon-tag"></span>
      <strong>$<%= @product.price %></strong>
    </p>
   
   <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
   <% end %> <!-- cache block-->
   <%= form_tag "/payments/create" do %>
     <%= render partial: "shared/stripe_checkout_button" %>
   <% end %>
 </div>


<div class="row">

<% unless (@product.comments.first.blank? ) %>
  <%= render partial: "comments" %>
<% else %>
  <p class="alert text-info">No comments yet. Be the first to review this product.</p>
<% end %>

<%= render partial: "new_comment" %>

</div>

  <hr>
<div class="buttons">
   <p><%= link_to 'Edit', edit_product_path(@product), class: "btn btn-default navbar-btn" %>| <%= link_to'Back', products_path, class: "btn btn-default navbar-btn" %></p>
</div>

</div>