config/routes.rb
Rails.application.routes.draw do

  resources :products do
    resources :comments
  end
  resources :users

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  devise_scope :user do
    get '/users', to: "devise/sessions#create"
  end

  resources :orders, only: [:index, :show, :create, :destroy]

  resources :payments
  post 'payments/create'
  
  post 'orders/show'

  get 'static_pages/about'

  get 'static_pages/contact'
  post 'static_pages/thank_you'

  get 'static_pages/index'

  
  
  root 'static_pages#landing_page'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cfapp</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<!-- <script src="../app/assets/javascripts/temp_alert.js"></script>  -->

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>


  <% if notice %>
    <p id="notice" class="alert alert-info"><%= notice %></p>
  <% end %>
   <script>
    setTimeout("$('#notice').fadeOut('slow')", 1000)
  </script>

<nav>
  <ul>
<!--     <li><a href="../static_pages/index.html">Home</a></li>
    <li><a href="../static_pages/about.html">About</a></li>
    <li><a href="../static_pages/contact.html">Contact</a></li>
    <li><a href="../../products">Products</a></li>
    <li><a href="../../orders">Orders</a></li> -->
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', static_pages_about_path %></li>
    <li><%= link_to 'Contact', static_pages_contact_path %></li>
    <li><%= link_to 'Products', products_path %></li>
    <li><%= link_to 'Orders', orders_path %></li>
  </ul>

<!-- login -->
<ul class="pull-right hmenu">
  <%= render 'devise/login_items' %>
  <%= render 'devise/registration_items' %>  
</ul>

<!-- search -->
<%= form_tag("/products", method: "get",class: "navbar-form navbar-left", role: "search") do %>
  <div class="form-group">
  <%= text_field_tag(:q, nil, class: "form-control", placeholder: "Product Search") %>
  </div>
  <%= submit_tag("Search", class: "btn btn-default") %>
<% end %>

<hr>
</nav>
  <%= flash[:notice] %>
<%= yield %>

<footer>
  &copy; 2015 Cecilia Zhang
</footer>

</body>
</html>